# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

DEBS_TARBALL = struct(
    revision = "1598549524",
    sha256 = "96539a26b73a41fcee40e6454de43eef6b97e7a83889bafb6dec6536fa06a1bc",
)

CACERTS = struct(
    revision = "1598549524",
    sha256 = "022e5d54dd70611a5025be88e339e973c1847eab5d6861df4aaa1ab04e00ddc4",
)
