# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

DEBS_TARBALL = struct(
    revision = "1598549524",
    sha256 = "a3e1c95d215cad3f173d4f79e5aa6738225018d846d373f59d9f63d0cfd7585a",
)

CACERTS = struct(
    revision = "1598549524",
    sha256 = "f224d63868d8aaa7e092686116b69e107b533396a7ee4ee9a5c404fa243ce0e3",
)
